### ISSUE TITLE
Port to serde 1.x

### ISSUE THREAD

**Issue by ignatenkobrain** [tapeinosyne/hyphenation#12]
There's serde 1.0 which is stable release, so would be awesome to see hyphenation ported to it.

**Comment by tapeinosyne** [comment]
Yes, using an established version of serde is highly desirable. The breaking changes introduced by serde 1.0 and bincode 0.8 are trivial, and they have already been addressed in a large backlog of commits. I will try to publish the new release this weekend.

**Comment by ignatenkobrain** [comment]
@tapeinosyne any news here?

**Comment by tapeinosyne** [comment]
The next release of`hyphenation` works with Serde 1.0 and will be published this weekend. Apologies for the long delay.

**Comment by kpcyrd** [comment]
hey, any updates here?

**Comment by infinity0** [comment]
Hey, we're asking because we're trying to add this package to Fedora and Debian, and updating to serde 1.0 would avoid us having to package the whole dependency tree of serde 0.8.

**Comment by tapeinosyne** [comment]
Long-overdue version 0.7 has been released and depends on stable serde.

**Comment by kpcyrd** [comment]
@tapeinosyne thanks! hopefully the last change required is this PR https://github.com/tapeinosyne/atlatl/pull/1 for a dependency of hyphenation.
